### ISSUE TITLE
Customer Help and Feedback Here!

### ISSUE THREAD

**Issue by knightad10** [MIATECHPARTNERS/PromptChains#2]
Hey there to everyone at MiatechPartners, I just purchased premium access to your prompt chain prompt queue tool here in Google as the extension. Now I followed the instructions correctly, I used straight from the GitHub examples even, and the multiple prompt chaining doesn't want to function for me. This is for the bulk upload area where you can seperate them out, and still nothing even with proper formatting and symbol use. Please help me either that the extension isn't functioning correctly or I am doing something wrong on my end. Please look into this when you can, I feel a little down that I went for the upgrade.

Best,
A

**Comment by Robsars** [comment]
Hey, I had the same issue when I first installed it a few weeks ago. What you can try is go to the chrome web store and remove the extension, and then reinstall it. Finally, refresh the browser. Hope that helps.

**Comment by JoelCCodes** [comment]
@knightad10 @Robsars  Sorry for the delayed response. ChatGPT made some updates to the UI that I had to update the extension. Version 7.2 should be working now, otherwise let me know and sorry for the delay!
